### ISSUE TITLE
Enhancement: Add ability to mention a custom path where the can be downloaded.

### ISSUE THREAD

**Issue by MASTERAMARJEET** [ParthBibekar/Welearn-bot#4]
## Why?
Given that this is to be used as a script. One should be able to run it from anywhere and store the files in a predefined path. As of now, it downloads them in the directory from where the script is run.

## Possible features:
- A `prefix` setting in `preference` section in `.welearnrc`
- A `-p` flag while running the script to save to a custom path. This should overwrite the `prefix` if already set in `.welearnrc`

**PS:** I was about to implement this but @sahasatvik is working on switching to using moodle API. This would change the details of the implementation. I would start after all such major changes are done.

**Comment by sahasatvik** [comment]
Please feel free to go ahead! In fact, I was just working on a flag/setting suggested by @ParthBibekar to specify filetypes to ignore, maybe put it under a `files` section?

**Comment by MASTERAMARJEET** [comment]
Yeah, a `files` section would work.
